In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
from folium.plugins import HeatMap, MarkerCluster
from wordcloud import WordCloud
from scipy.stats import zscore
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest

In [2]:
df = pd.read_csv("/Users/smriti/ride-hailing-safety-project/datasets/raw/ride_safety_dataset.csv")
df.head(5)

,Crime_ID,City,Date,Time,Crime_Type,Location,Latitude,Longitude,Crime_Severity,Police_Response_Time_Minutes,...,Weather_Condition,Traffic_Congestion_Level,Traffic_Avg_Speed_KMH,Road_Accidents_Reported,Nearby_CCTV_Cameras,Uber_Ola_Route_Overlap,Public_Complaints,Time_of_Day,Passenger_Gender,Num_Police_Stations_Nearby
0,1,Delhi,2023-01-24,10:14,Harassment,Juhu,24.334915,74.104214,1.0,2,...,Rainy,8,48.082783,4,8,1,3,Night,Female,4
1,2,Mumbai,2024-04-08,02:39,Burglary,Saket,22.361341,73.300546,8.0,54,...,Foggy,9,39.319294,2,6,1,5,Morning,Male,4
2,3,Delhi,2023-12-04,09:46,Fraud,Bandra,24.694028,75.513084,10.0,12,...,Cloudy,3,44.654822,2,3,1,0,Morning,Male,2
3,4,Delhi,2023-10-14,22:38,Harassment,Lajpat Nagar,23.201538,74.088573,3.0,40,...,Foggy,3,8.001502,2,7,0,3,Morning,Female,2
4,5,Delhi,2023-01-03,14:37,Theft,Dwarka,25.207312,75.944358,4.0,2,...,Rainy,5,50.073347,0,0,1,5,Night,Male,1

In [3]:
df.columns

Index(['Crime_ID', 'City', 'Date', 'Time', 'Crime_Type', 'Location',
       'Latitude', 'Longitude', 'Crime_Severity',
       'Police_Response_Time_Minutes', 'Resolved', 'Suspect_Arrested',
       'Ride_ID', 'Ride_Date', 'Ride_Time', 'Pickup_Location', 'Drop_Location',
       'Ride_Duration_Minutes', 'Distance_KM', 'Ride_Fare_INR',
       'Ride_Surge_Pricing_Factor', 'Driver_Rating',
       'Ride_Cancellation_Status', 'Weather_Temperature_C',
       'Weather_Rainfall_mm', 'Weather_Visibility_KM', 'Weather_Humidity_%',
       'Weather_Wind_Speed_KMH', 'Weather_Condition',
       'Traffic_Congestion_Level', 'Traffic_Avg_Speed_KMH',
       'Road_Accidents_Reported', 'Nearby_CCTV_Cameras',
       'Uber_Ola_Route_Overlap', 'Public_Complaints', 'Time_of_Day',
       'Passenger_Gender', 'Num_Police_Stations_Nearby'],
      dtype='object')

In [8]:
selected_columns = [
    "Crime_Type", "Crime_Severity", "Police_Response_Time_Minutes", "Resolved", "Suspect_Arrested", "Public_Complaints", "Location",
    "Ride_Duration_Minutes", "Ride_Fare_INR", "Ride_Surge_Pricing_Factor", "Driver_Rating", "Ride_Cancellation_Status",
    "Weather_Temperature_C", "Weather_Visibility_KM", "Weather_Humidity_%", "Weather_Wind_Speed_KMH", "Weather_Condition",
    "Road_Accidents_Reported", "Nearby_CCTV_Cameras", "Time_of_Day", "Num_Police_Stations_Nearby"
]

train_df = df[selected_columns]

train_df.head()

,Crime_Type,Crime_Severity,Police_Response_Time_Minutes,Resolved,Suspect_Arrested,Public_Complaints,Location,Ride_Duration_Minutes,Ride_Fare_INR,Ride_Surge_Pricing_Factor,...,Ride_Cancellation_Status,Weather_Temperature_C,Weather_Visibility_KM,Weather_Humidity_%,Weather_Wind_Speed_KMH,Weather_Condition,Road_Accidents_Reported,Nearby_CCTV_Cameras,Time_of_Day,Num_Police_Stations_Nearby
0,Harassment,1.0,2,1,1,3,Juhu,97,275.069731,2.0,...,Cancelled,31.960278,3.283636,69,37,Rainy,4,8,Night,4
1,Burglary,8.0,54,1,0,5,Saket,105,1008.617851,1.2,...,Completed,34.393834,1.476428,67,6,Foggy,2,6,Morning,4
2,Fraud,10.0,12,1,1,0,Bandra,6,638.746493,1.0,...,Completed,30.661429,5.489576,64,24,Cloudy,2,3,Morning,2
3,Harassment,3.0,40,0,1,3,Lajpat Nagar,52,1000.684402,1.5,...,Completed,41.605092,3.771492,98,49,Foggy,2,7,Morning,2
4,Theft,4.0,2,0,1,5,Dwarka,5,1144.446359,1.5,...,Completed,32.917257,5.851538,85,26,Rainy,0,0,Night,1

In [9]:
train_df.to_csv('train.csv')

In [10]:
def calculate_risk_factor():
    pass

In [11]:
train_df['Location'].unique()

array(['Juhu', 'Saket', 'Bandra', 'Lajpat Nagar', 'Dwarka',
       'Connaught Place', 'Karol Bagh', 'Colaba', 'Dadar', 'Andheri'],
      dtype=object)

In [ ]:
train_df.info()

In [15]:
len(df[df["City"] == "Delhi"])

2504

In [16]:
len(df[df["City"] == "Mumbai"])

2496